name = "woocommerce-cache-worker"
main = "index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
# Routes are managed via Cloudflare dashboard
# routes = [
#   "example.com/*",
#   "www.example.com/*"
# ]

# Development/Testing environment
[env.development]
routes = [
  # Use a testing subdomain that doesn't affect production
  # "test.example.com/*",
  # "staging.example.com/*"
]

# Local development variables
[vars]
# ORIGIN_URL = "https://your-woocommerce-site.com"  # Uncomment and set for testing
